modLoader="javafml"

loaderVersion="[44,)"

license="All rights reserved"

[[mods]]

modId="endadventure"

version="1.0"

displayName="End Adventure"

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="examplemod.png"

credits="Made by DrNickenstein"

authors="DrNickenstein"

description='''End expansion mod'''
